### PR TITLE
tft.py Reduce allocation when using transparency

### PR DESCRIPTION
**Pull request by peterhinch**
Hi Robert, when using transparency this patch avoids allocating a buffer each time a string is output. The drawback is that the buffer remains in place, potentially after the need for it has passed. However in typical GUI applications strings are drawn repeatedly and it saves a lot of allocs which can eventually fail if the heap becomes fragmented.

### CODE REVIEW

**Comment by robert-hh** [comment]
Hi Peter, thanks for the PR. Preallocating the buffer is surely an efficiency improvement. Did you keep the row-by-row pixel structure I use in the fonts? Otherwise the displaySCR_charbitmap() function in TFT_io.py wouldn't work. I must say I lost that project a little bit out of sight, and hardly remember all the little details. The age, you know ...

**Comment by peterhinch** [comment]
Hi Robert, I think age has got the better of me this time.

When I created the branch I'd forgotten that my fork has diverged significantly from yours, so the PR includes a heap of changes I hadn't intended to include. If you look at the last commit you'll see that the change is very simple. It radically reduced OOM errors when running my GUI on a very fragmented Pyboard where it tried to allocate ~2K each time a screen was refreshed. However I can envisage applications where it could actually make things worse. It is, of course, entirely up to you whether to make the change.

These display boards seem harder to find these days so I don't know how many new users we're likely to get.

**Comment by robert-hh** [comment]
Hi Peter, I noticed the change to tft.py, and it looks good to me. To a certain extend, that was possible before too, because the caller of Print_char could supply a preallocated buffer. But your solution makes using it easier and more robust.
The TFT's are still available at buydisplay.com. They deliver pretty fast. Another source is www.eckstein-shop.de. I thought a while of rebuilding the lib using SPI and thge ILI3941 controller. But there is not need at the moment, especially since there are already libs offering that. They seem however lack a good font handling.

**Comment by robert-hh** [comment]
I have included the preallocation of the buffer required for transparency into my branch. Including the other changes is a little bit too much at the moment.

**Comment by peterhinch** [comment]
Fair enough - it was my error to include them in the PR.

**Pull request closed without merging**
